# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the /
# first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the /
# even-valued terms.
MAXIMUM = 4000000


def main():
    fibonacci = list()
    amount = 100
    n1, n2 = 0, 1
    count = 0
    while count < amount:
        fibonacci.append(n1)
        nth = n1 + n2
        n1 = n2
        n2 = nth
        count += 1
        if nth > MAXIMUM:
            fibonacci.append(n1)
            break

    even_numbers = list()

    for number in fibonacci:
        if number % 2 == 0:
            even_numbers.append(number)

    sum_even = sum(even_numbers)

    print("The Fibonacci sequence is: ", fibonacci)
    print("The even numbers are: ", even_numbers)
    print("The sum of even numbers in Fibonacci sequence in range 4000000 is", sum_even)
    

main()
